### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by j2l** [rse/node-red-contrib-functionx#2]
Hello,
On node-red 1.2.6, I tried your example:
```
var { lowerCase } = require("upper-case");
msg.payload = {             
    lower: lowerCase("Hello World")
}
return msg;
```
and get "TypeError: lowerCase is not a function"

Any idea why?

**Comment by DoHaiSon** [comment]
With me, nothing happen T.T, not msg.payload, not err, just nothing.

**Comment by j2l** [comment]
Try with simple quotes:
```
var { lowerCase } = require('lower-case');
msg.payload = {             
    lower: lowerCase("Hello World")
}
return msg;
```

**Comment by DoHaiSon** [comment]
> 
> 
> Try with simple quotes:
> 
> ```
> var { lowerCase } = require('lower-case');
> msg.payload = {             
>     lower: lowerCase("Hello World")
> }
> return msg;
> ```

I don't know why but still nothing in debug window

**Comment by j2l** [comment]
I have no idea why too.
Check your NR logs. Usually you see loading libraries in there.

**Comment by DoHaiSon** [comment]
Im working in an IoT Gateway that pre installed node red. And I communicate with this by a web client so I think I cannot open log T.T
